[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"  # Change from 18 to 20

[functions]
  directory = "netlify/functions"
  # Remove the included_files line that includes node_modules

# Your existing headers and redirects...
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.mymemory.translated.net https://libretranslate.de https://translate.googleapis.com"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/kannada-dictionary.db"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/octet-stream"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200