# netlify.toml

[build]
  # Build command for React app
  command = "npm run build"
  # Directory with built files
  publish = "dist"
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Redirects and rewrites
[[redirects]]
  # Handle React Router (SPA)
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.mymemory.translated.net https://libretranslate.de https://translate.googleapis.com"

# Headers for static files
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for database file
[[headers]]
  for = "/kannada-dictionary.db"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/octet-stream"

# Function-specific settings
[functions.translate]
  included_files = ["node_modules/**"]